services:
  - postgresql95

install:
- ps: >-
    SET PGUSER=postgres
    SET PGPASSWORD=Password12!
    PATH=C:\Program Files\PostgreSQL\9.5\bin\;%PATH%
    createdb rebus2_test

before_build:
  - nuget restore